apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardapi
  labels:
    app: board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "boardapi"
        dapr.io/app-port: "8080"
        dapr.io/app-protocol: "grpc"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: board
        image: othello/board:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Never