# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cp_pb2 as cp__pb2


class CpApiStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Attack = channel.unary_unary(
                '/cp.CpApi/Attack',
                request_serializer=cp__pb2.Cp.SerializeToString,
                response_deserializer=cp__pb2.Res.FromString,
                )


class CpApiServicer(object):
    """The greeting service definition.
    """

    def Attack(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CpApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Attack': grpc.unary_unary_rpc_method_handler(
                    servicer.Attack,
                    request_deserializer=cp__pb2.Cp.FromString,
                    response_serializer=cp__pb2.Res.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cp.CpApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CpApi(object):
    """The greeting service definition.
    """

    @staticmethod
    def Attack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cp.CpApi/Attack',
            cp__pb2.Cp.SerializeToString,
            cp__pb2.Res.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
